namespace :files do
	desc 'takes a file with a suffix .yaml and changes it to .yml'
	task :rename_yml do
	    file = ENV["MYPATH"]
	    source = File.new(file, "r+")
	    dirname  = File.dirname(source)
	    basename = File.basename(source, ".*")
	    extname  = File.extname(source)
	    puts "Old file name: " + file
	    if extname == ""
	        if basename[0,1]=="."
	                target = dirname + "/.yml"
	                else
	                target = source + ".yml"
	        end
	    else
			    target = dirname + "/" + basename + ".yaml"
	    end
	    File.rename(source, target)
	    puts "New file name: " + target
	    target
    end
end
